//! Turn upstream's built web bundle into a table of names and bytes that live
//! in the executable.
//!
//! Ticket 23 asks for a UI served "from the embedded application rather than a
//! development server", and this is the embedding. There is no crate for it
//! because there does not need to be: what is wanted is a list of
//! `include_bytes!` calls, and generating one is a dozen lines that also buy the
//! two things an off-the-shelf embedder would not give — a filter, and a failure
//! that says what to do.
//!
//! **Source maps are excluded.** `dist/` is 54 MB, of which 37 MB is `.map`
//! files: debug data for vendored JavaScript this project does not debug, which
//! nothing loads unless a developer opens the devtools. Shipping them would put
//! the artifact at three times the 20–30 MB target on its own. Everything else
//! upstream built is shipped exactly as built — trimming the bundle itself is a
//! change to vendored code that ticket 24 records as needing its own decision.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let bundle = bundle_directory();
    let manifest = web_directory().join("package.json");
    println!("cargo::rerun-if-changed={}", bundle.display());
    println!("cargo::rerun-if-changed={}", manifest.display());

    let mut files = Vec::new();
    collect(&bundle, &bundle, &mut files);
    files.sort();

    if files.is_empty() {
        panic!(
            "no web assets under {}.\n\
             \n\
             lightcode's window shows upstream's built UI, which lives in the vendored\n\
             t3code checkout and is not committed to this repository. Build it there\n\
             (`pnpm install && pnpm --filter @t3tools/web build` in t3code/) and try again.\n\
             The server itself needs none of this: `cargo run -p lightcode-server` is a\n\
             socket endpoint with no window.",
            bundle.display()
        );
    }

    let mut generated = String::from(
        "// Generated by build.rs. The web bundle, as names and bytes.\n\
         pub static FILES: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &files {
        writeln!(
            generated,
            "    ({name:?}, include_bytes!(r\"{}\")),",
            path.display()
        )
        .expect("writing to a string cannot fail");
    }
    generated.push_str("];\n");

    writeln!(
        generated,
        "\n/// The version `t3code/apps/web/package.json` gives the bundle above.\n\
         /// Ticket 26: the server reports this as its own, because it is the\n\
         /// number that UI compares against.\npub static VERSION: &str = {:?};",
        bundle_version(&manifest)
    )
    .expect("writing to a string cannot fail");

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    std::fs::write(out.join("assets.rs"), generated).expect("the generated table is written");

    tauri_build::build();
}

/// Where upstream's `dist/` is, relative to this crate.
///
/// A path rather than a search: `t3code/` is a vendored checkout at a known
/// place in this repository, and looking for it anywhere else would mean
/// embedding whatever happened to be lying around.
fn bundle_directory() -> PathBuf {
    web_directory().join("dist")
}

/// The web package the bundle was built from — `dist/`'s own directory, and
/// where `package.json` is.
fn web_directory() -> PathBuf {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    manifest
        .join("..")
        .join("..")
        .join("t3code")
        .join("apps")
        .join("web")
}

/// What the UI calls itself: `package.json`'s `version`.
///
/// Ticket 26 makes this the server's advertised `serverVersion`, because the
/// client compares that field against the same number compiled into its own
/// bundle and offers to relaunch the server when they differ — advice that
/// names no action when the server and the UI are one executable.
///
/// This is the manifest rather than the bundle because it is a number in a
/// field rather than a needle in minified JavaScript. Vite bakes the same value
/// in as `APP_VERSION` — unless the person who ran the build set that variable
/// — and `the_version_reported_is_the_one_the_ui_compares_against` in `main.rs`
/// is what checks the two did not part company.
///
/// A failure here is a panic rather than a fallback for the same reason the
/// missing-bundle failure above is: a shell built with a version it had to
/// guess would ship the banner back, silently, and the read is of a file that
/// is necessarily there — `dist/` was built from it.
fn bundle_version(manifest: &Path) -> String {
    let source = std::fs::read_to_string(manifest).unwrap_or_else(|error| {
        panic!(
            "cannot read {}: {error}.\n\
             \n\
             This is upstream's web package manifest, beside the `dist/` this build\n\
             embeds. lightcode reports the version it names as its own server version,\n\
             so that the UI does not warn about a skew between itself and the binary\n\
             it is part of.",
            manifest.display()
        )
    });

    let package = serde_json::from_str::<serde_json::Value>(&source).unwrap_or_else(|error| {
        panic!("{} is not readable as json: {error}", manifest.display())
    });

    package
        .get("version")
        .and_then(serde_json::Value::as_str)
        .map(|version| version.trim().to_string())
        .filter(|version| !version.is_empty())
        .unwrap_or_else(|| {
            panic!(
                "{} has no `version` string.\n\
                 \n\
                 It is what lightcode reports as its server version; without it the UI\n\
                 would compare its own version against nothing and warn about a skew.",
                manifest.display()
            )
        })
}

/// Every file under `directory`, as (bundle-relative name, absolute path).
fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let entries = match std::fs::read_dir(directory) {
        Ok(entries) => entries,
        // Missing entirely is the interesting case, and the caller reports it
        // with a sentence. An unreadable subdirectory is the same story with
        // less to say.
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, files);
            continue;
        }
        if path.extension().is_some_and(|extension| extension == "map") {
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        // URL paths, not filesystem paths: this name is what a request asks
        // for, and a request never carries a backslash.
        let name = relative
            .components()
            .map(|component| component.as_os_str().to_string_lossy())
            .collect::<Vec<_>>()
            .join("/");
        files.push((name, path));
    }
}
