//! Turn upstream's built web bundle into a table of names and bytes that live
//! in the executable.
//!
//! Ticket 23 asks for a UI served "from the embedded application rather than a
//! development server", and this is the embedding. There is no crate for it
//! because there does not need to be: what is wanted is a list of
//! `include_bytes!` calls, and generating one is a dozen lines that also buy the
//! two things an off-the-shelf embedder would not give — a filter, and a failure
//! that says what to do.
//!
//! **Source maps are excluded.** `dist/` is 54 MB, of which 37 MB is `.map`
//! files: debug data for vendored JavaScript this project does not debug, which
//! nothing loads unless a developer opens the devtools. Shipping them would put
//! the artifact at three times the 20–30 MB target on its own. Everything else
//! upstream built is shipped exactly as built — trimming the bundle itself is a
//! change to vendored code that ticket 24 records as needing its own decision.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let bundle = bundle_directory();
    println!("cargo::rerun-if-changed={}", bundle.display());

    let mut files = Vec::new();
    collect(&bundle, &bundle, &mut files);
    files.sort();

    if files.is_empty() {
        panic!(
            "no web assets under {}.\n\
             \n\
             lightcode's window shows upstream's built UI, which lives in the vendored\n\
             t3code checkout and is not committed to this repository. Build it there\n\
             (`pnpm install && pnpm --filter @t3tools/web build` in t3code/) and try again.\n\
             The server itself needs none of this: `cargo run -p lightcode-server` is a\n\
             socket endpoint with no window.",
            bundle.display()
        );
    }

    let mut generated = String::from(
        "// Generated by build.rs. The web bundle, as names and bytes.\n\
         pub static FILES: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &files {
        writeln!(
            generated,
            "    ({name:?}, include_bytes!(r\"{}\")),",
            path.display()
        )
        .expect("writing to a string cannot fail");
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    std::fs::write(out.join("assets.rs"), generated).expect("the generated table is written");

    tauri_build::build();
}

/// Where upstream's `dist/` is, relative to this crate.
///
/// A path rather than a search: `t3code/` is a vendored checkout at a known
/// place in this repository, and looking for it anywhere else would mean
/// embedding whatever happened to be lying around.
fn bundle_directory() -> PathBuf {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    manifest
        .join("..")
        .join("..")
        .join("t3code")
        .join("apps")
        .join("web")
        .join("dist")
}

/// Every file under `directory`, as (bundle-relative name, absolute path).
fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let entries = match std::fs::read_dir(directory) {
        Ok(entries) => entries,
        // Missing entirely is the interesting case, and the caller reports it
        // with a sentence. An unreadable subdirectory is the same story with
        // less to say.
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, files);
            continue;
        }
        if path.extension().is_some_and(|extension| extension == "map") {
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        // URL paths, not filesystem paths: this name is what a request asks
        // for, and a request never carries a backslash.
        let name = relative
            .components()
            .map(|component| component.as_os_str().to_string_lossy())
            .collect::<Vec<_>>()
            .join("/");
        files.push((name, path));
    }
}
