//! laplus, as a desktop application.
//!
//! The whole shell is this file, and that is the point of the design: the
//! server is a library that already knows how to serve the UI
//! ([`laplus_server::ui`]), so what is left for a window to do is start it,
//! point at it, and stop it.
//!
//! ```text
//! bind 127.0.0.1:4773  ──►  window at http://127.0.0.1:4773/
//!                                │
//!                           close the window
//!                                │
//!                           shutdown(): sockets, agents, terminals, transcripts
//! ```
//!
//! Four decisions are worth finding here rather than by reading around them.
//!
//! **The window is pointed at an ordinary loopback URL**, not at Tauri's
//! embedded-asset scheme. `laplus_server::ui` gives the reasoning; the short
//! version is that the page and the socket then share an origin, so nothing is
//! cross-origin, upstream's bundle is shipped exactly as it was built, and
//! `localStorage` belongs to the app rather than to a scheme handler.
//!
//! **The port is fixed**, for that last reason — see
//! [`laplus_server::launch`]. A port already taken is a refusal with a
//! sentence, because the usual desktop reflex of grabbing any free port would
//! change the origin on every launch and lose the developer's layout, drafts and
//! open thread each time, silently.
//!
//! **The version this application reports is the bundle's, not this crate's.**
//! `build.rs` reads it out of `apps/web/package.json` and it travels with
//! the bytes, so the server serves a UI and answers with that UI's number. The
//! reason is upstream's version-skew banner, and
//! [`laplus_server::config::ServerConfig::serving_ui_version`] is where the
//! whole of it is written down — including what it does *not* mean.
//!
//! **The window has no native decorations, and the UI draws its own titlebar.**
//! Ticket 27, and the three things it says have to happen together are the
//! three things here: `decorations(false)` below, the buttons in
//! `apps/web/src/components/DesktopWindowControls.tsx`, and
//! `capabilities/titlebar.toml`, which is what lets a page served over
//! loopback move the window it is in. Any one alone makes the application
//! worse — a frameless window with no buttons cannot be closed, and buttons
//! without the capability are three shapes that do nothing.
//!
//! Two things that had to be found out rather than assumed, and that decide the
//! shape of all three:
//!
//! **The UI cannot be told it is Electron.** Upstream's titlebar path is gated
//! on `apps/web/src/env.ts`, which asks whether Electron's preload bridge is
//! present — and the UI spends that answer on hash-history routing and on every
//! other call into a bridge this webview does not have. So the gate is a
//! separate `isDesktopShell`, keyed on Tauri's own `window.isTauri`, and it is
//! read by the titlebar and by nothing else. `apps/web/src/desktopShell.ts` has
//! the whole argument.
//!
//! **Upstream's Windows titlebar path could not have been switched on anyway.**
//! It reserves space for buttons the *operating system* draws, through
//! `navigator.windowControlsOverlay` and `env(titlebar-area-*)`. WebView2
//! exposes no Window Controls Overlay at all — not a different one, none — so
//! that path is waiting for a browser API that will not arrive here, and the
//! buttons have to be a component.
//!
//! `-webkit-app-region: drag`, which upstream marks its topbars with, is inert
//! in WebView2 for the same family of reasons. The topbars carry
//! `data-tauri-drag-region` as well, which Tauri's own injected script acts on.

// A released laplus is a window, so it is not also a console: without this
// Windows gives the process one, and the developer gets a black rectangle
// beside their application for the life of it. A debug build keeps its console
// on purpose — that is where `println!` goes, and where a developer running the
// shell by hand is looking. What the released build loses by it is anything
// this process says before a window exists, which is why [`fail`] also writes
// to a file.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::io::Write as _;
use std::process::ExitCode;
use std::sync::Mutex;

use laplus_server::launch;
use laplus_server::ui::Assets;
use laplus_server::Server;

/// The web bundle: `pub static FILES: &[(&str, &[u8])]` and the `VERSION` it
/// was built as, generated by `build.rs` from `apps/web`.
mod assets {
    include!(concat!(env!("OUT_DIR"), "/assets.rs"));
}

fn main() -> ExitCode {
    let port = match launch::requested_port() {
        Ok(port) => port,
        Err(message) => return fail(&message),
    };

    // One runtime for the process, holding the server for as long as the window
    // is open. `new_multi_thread` and not the current thread's: the event loop
    // below belongs to the operating system and never yields to a scheduler, so
    // the server needs threads of its own to be served on at all.
    let runtime = match tokio::runtime::Builder::new_multi_thread().enable_all().build() {
        Ok(runtime) => runtime,
        Err(error) => return fail(&format!("cannot start a runtime: {error}")),
    };

    let ui = Assets::from_static(assets::FILES, assets::VERSION);
    let server = match runtime.block_on(Server::bind(port, ui)) {
        Ok(server) => server,
        Err(failure) => return fail(&format!("{failure}")),
    };

    println!("laplus: serving {}", server.http_url());

    // The window opens on a URL carrying the credential it will authenticate
    // with, in the fragment — which the browser keeps and never sends, so the
    // credential reaches this window and nothing that merely reaches this
    // server. `Server::window_url` is where that is argued.
    //
    // Falling back to the plain URL when the boot grant could not be minted
    // opens the pairing screen rather than nothing at all.
    let url = server.window_url().unwrap_or_else(|| server.http_url());

    // Taken exactly once, by whichever of the two exit events arrives first.
    let server = Mutex::new(Some(server));

    let application = tauri::Builder::default()
        // Ticket 74. The plugin is registered here and driven entirely from the
        // page: `capabilities/updater.toml` grants its commands to the loopback
        // origin, and `apps/web/src/desktopUpdate.bridge.ts` is what presses
        // them. Nothing checks for an update on this side, because nothing here
        // would have anywhere to report the answer — the pill that shows it is
        // the UI's.
        .plugin(tauri_plugin_updater::Builder::new().build())
        .setup(move |app| {
            window(app, &url)?;
            Ok(())
        })
        .build(tauri::generate_context!());

    let application = match application {
        Ok(application) => application,
        Err(error) => {
            // The window never opened, so nothing is holding the server but
            // this function. Stop it properly rather than exiting over the top
            // of it.
            if let Some(server) = server.lock().ok().and_then(|mut held| held.take()) {
                runtime.block_on(server.shutdown());
            }
            return fail(&format!("cannot open a window: {error}"));
        }
    };

    application.run(move |_app, event| {
        // `ExitRequested` is the last window closing; `Exit` is the process on
        // its way out however it got there. Both are handled because a
        // `claude` or a shell outliving this process is the one leak that
        // survives it — see `Server::shutdown`, which is where the reaping and
        // its order actually live.
        if matches!(
            event,
            tauri::RunEvent::ExitRequested { .. } | tauri::RunEvent::Exit
        ) {
            if let Some(server) = server.lock().ok().and_then(|mut held| held.take()) {
                runtime.block_on(server.shutdown());
            }
        }
    });

    ExitCode::SUCCESS
}

/// The one window.
///
/// Built here rather than declared in `tauri.conf.json` because its URL is not
/// known until the listener is bound — the configuration cannot name a port the
/// developer may have overridden.
fn window(app: &tauri::App, url: &str) -> tauri::Result<()> {
    let url = url
        .parse()
        .expect("the server's own address is a valid url");

    tauri::WebviewWindowBuilder::new(app, "main", tauri::WebviewUrl::External(url))
        .title("laplus")
        .inner_size(1440.0, 900.0)
        // Below this the UI's three panes stop having room to be three panes.
        .min_inner_size(800.0, 600.0)
        // Ticket 27: one bar at the top of the window rather than two. What
        // replaces the frame is drawn by the page — see the note at the top of
        // this file, and `capabilities/titlebar.toml` for what that page is
        // allowed to do to this window. The label above is what that capability
        // names, so renaming the window revokes its titlebar.
        .decorations(false)
        .build()?;

    Ok(())
}

/// Report a failure that happened before there was a window to report it in,
/// and stop.
///
/// A released build has no console, so `stderr` alone would mean an application
/// that does nothing when double-clicked and says nothing about why. The file is
/// the one the server already advertises to the UI as `logsDirectoryPath`, so
/// this lands where a developer looking for laplus's logs is already looking
/// — and where a `logs` directory is already made.
///
/// Best-effort by design: if this cannot write the file it has nothing better to
/// try, and a shell that panicked while reporting a failure would replace a
/// legible problem with an illegible one.
fn fail(message: &str) -> ExitCode {
    eprintln!("laplus: {message}");

    let logs = laplus_server::config::logs_dir();
    if std::fs::create_dir_all(&logs).is_ok() {
        if let Ok(mut file) = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(logs.join("startup.log"))
        {
            let _ = writeln!(file, "laplus did not start: {message}");
        }
    }

    ExitCode::FAILURE
}

/// What this crate contributes that the server cannot check for itself: the
/// bundle that ends up in the executable.
///
/// Everything about *serving* it is tested in `laplus_server::ui` and
/// `tests/http_ui.rs` against three files. These are about the four hundred —
/// that they are there, that they are the right four hundred, and that they go
/// through the same policy the three did.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_ui_is_in_the_binary() {
        assert!(
            assets::FILES.len() > 100,
            "a web bundle is hundreds of files, not {}",
            assets::FILES.len()
        );
        let (_, page) = assets::FILES
            .iter()
            .find(|(name, _)| *name == "index.html")
            .expect("the bundle has an entry point");
        assert!(
            String::from_utf8_lossy(page).contains("<script"),
            "the entry point should load the application"
        );
    }

    /// 37 MB of the 54 MB upstream builds is debug data for JavaScript this
    /// project does not debug. Shipping it would miss the size target three
    /// times over on its own, which is the target the project exists for.
    #[test]
    fn no_source_maps_are_shipped() {
        let maps: Vec<&str> = assets::FILES
            .iter()
            .map(|(name, _)| *name)
            .filter(|name| name.ends_with(".map"))
            .collect();
        assert!(maps.is_empty(), "source maps in the artifact: {maps:?}");
    }

    /// Ticket 23's "no Node runtime is present in the built application".
    ///
    /// The strong form of that is structural and holds by construction — this
    /// is one Rust executable, and nothing in the build runs or ships a
    /// JavaScript runtime. What is worth checking is the way it could stop
    /// being true without anyone noticing: upstream's bundle is copied in
    /// wholesale, and a native addon or a stray `node_modules` tree appearing
    /// in `dist/` would be embedded along with everything else.
    #[test]
    fn no_node_runtime_is_shipped() {
        let smuggled: Vec<&str> = assets::FILES
            .iter()
            .map(|(name, _)| *name)
            .filter(|name| {
                name.ends_with(".node")
                    || name.ends_with(".exe")
                    || name.ends_with(".dll")
                    || name.split('/').any(|segment| segment == "node_modules")
            })
            .collect();
        assert!(smuggled.is_empty(), "a runtime came with the UI: {smuggled:?}");
    }

    /// The names are what an HTTP request asks for, and this build script runs
    /// on Windows, where a path separator is the other one.
    #[test]
    fn every_name_is_a_url_path_rather_than_a_file_path() {
        for (name, _) in assets::FILES {
            assert!(!name.contains('\\'), "{name} is a file path");
            assert!(!name.starts_with('/'), "{name} is absolute");
        }
    }

    /// Ticket 26. The server reports [`assets::VERSION`] as its own so that the
    /// UI's skew banner has nothing to say, which only works if that number is
    /// the one the UI is comparing it against — and the two are read from
    /// different places. `build.rs` takes it from `package.json`; the bundle got
    /// it from Vite, which prefers an `APP_VERSION` environment variable over
    /// the same field. A `dist/` built with that variable set would put the
    /// banner back, and nothing else here would notice.
    #[test]
    fn the_version_reported_is_the_one_the_ui_compares_against() {
        assert_eq!(assets::VERSION, assets::VERSION.trim());
        assert!(!assets::VERSION.is_empty(), "the bundle has no version");

        // `APP_VERSION:` and its value, as a minified bundle spells the object
        // Vite substitutes for `import.meta.env`. The quoting is the minifier's
        // business, so this looks in the neighbourhood rather than for an exact
        // string — by characters, because minified JavaScript is full of
        // multibyte ones and a byte-sliced window would land inside one.
        let mut sightings = 0;
        let mut agreeing = 0;
        for (_, bytes) in assets::FILES.iter().filter(|(name, _)| name.ends_with(".js")) {
            let source = String::from_utf8_lossy(bytes);
            for (at, _) in source.match_indices("APP_VERSION") {
                sightings += 1;
                let neighbourhood: String = source[at..].chars().take(64).collect();
                if neighbourhood.contains(assets::VERSION) {
                    agreeing += 1;
                }
            }
        }

        assert!(
            sightings > 0,
            "no APP_VERSION in the bundle: this test's needle has gone stale, and \
             the check it stands for is not being made"
        );
        // One sighting is enough, and asking for all of them would be a stricter
        // test of something else: every `APP_VERSION` in the bundle is the same
        // substitution, so a `dist/` built with the environment variable set has
        // *none* that agree — while a spelling this needle does not recognise
        // would fail a stricter assertion for no reason.
        assert!(
            agreeing > 0,
            "none of the {sightings} APP_VERSION sightings in the bundle carry {}, \
             which is what this server will report — the UI will warn about a \
             version skew on every launch",
            assets::VERSION
        );
    }

    /// Ticket 27. A frameless window is moved and closed entirely through the
    /// IPC, and the IPC checks the page's origin against this file — so a
    /// capability that names the wrong origin is a window that cannot be
    /// dragged, minimised or closed, with nothing on screen to say why. The
    /// grant is to a *remote* origin because the window is pointed at loopback
    /// rather than at a Tauri scheme (ADR-0010), which is the part that is easy
    /// to get wrong and impossible to notice from the code.
    ///
    /// This asserts against the address `Server::http_url` actually produces
    /// rather than against a copy of it, and against an overridden port as well
    /// as the default, because `--port` and `LAPLUS_PORT` both move it.
    /// Read a capability through Tauri's own loader rather than a copy of the
    /// file's contents, so this is the same parse `tauri_build` makes of the
    /// same bytes — a capability that fails to load is a build failure there and
    /// has to be one here too, not a test that quietly asserts nothing.
    fn capability(name: &str) -> tauri::utils::acl::capability::Capability {
        use tauri::utils::acl::capability::CapabilityFile;

        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("capabilities")
            .join(format!("{name}.toml"));
        let file = CapabilityFile::load(&path).expect("the capability file parses");
        let CapabilityFile::Capability(capability) = file else {
            panic!("{name}.toml is one capability, not a list");
        };
        capability
    }

    /// Whether a capability's `[remote]` section covers a given URL, answered by
    /// the same pattern matcher the IPC uses.
    fn covers(capability: &tauri::utils::acl::capability::Capability, url: &str) -> bool {
        let remote = capability
            .remote
            .as_ref()
            .expect("a page served over http is a remote origin to the IPC");
        let patterns: Vec<tauri::utils::acl::RemoteUrlPattern> = remote
            .urls
            .iter()
            .map(|url| url.parse().expect("a valid url pattern"))
            .collect();
        let url = url.parse().expect("a valid url");
        patterns.iter().any(|pattern| pattern.test(&url))
    }

    /// Ticket 74. The update pill is the same failure mode as the titlebar's
    /// buttons — a control that renders correctly and does nothing — so the
    /// grant that makes it work is asserted here rather than discovered by
    /// waiting for a release and pressing it.
    ///
    /// The commands are named individually because the set is deliberately not
    /// `updater:default`: that would also grant `download_and_install`, a path
    /// nothing presses, and the two-press download-then-restart shape is the
    /// pill's.
    #[test]
    fn the_page_may_check_for_download_and_install_an_update() {
        let updater = capability("updater");

        let default = format!("http://127.0.0.1:{}/", laplus_server::launch::DEFAULT_PORT);
        assert!(covers(&updater, &default), "the capability does not cover {default}");
        assert!(covers(&updater, "http://127.0.0.1:4774/"), "an overridden port");
        // Replacing this application is not something an origin off this machine
        // may ask for, whatever else it is allowed.
        assert!(!covers(&updater, "https://example.com/"), "an origin off this machine");

        let granted: Vec<String> = updater
            .permissions
            .iter()
            .map(|permission| permission.identifier().get().to_string())
            .collect();
        for needed in [
            "updater:allow-check",
            "updater:allow-download",
            "updater:allow-install",
        ] {
            assert!(
                granted.iter().any(|identifier| identifier == needed),
                "{needed} is not granted: the pill that presses it does nothing"
            );
        }
    }

    #[test]
    fn the_capability_covers_the_origin_the_server_serves() {
        let capability = capability("titlebar");

        // The default, spelled the way the server spells it.
        let default = format!("http://127.0.0.1:{}/", laplus_server::launch::DEFAULT_PORT);
        assert!(covers(&capability, &default), "the capability does not cover {default}");
        // And a port a developer moved it to.
        assert!(covers(&capability, "http://127.0.0.1:4774/"), "an overridden port");
        // The host is not a wildcard, and should not become one: this grant is
        // the right to move somebody's window.
        assert!(!covers(&capability, "https://example.com/"), "an origin off this machine");

        // Naming a command the UI presses is what makes the button work, so the
        // list is asserted rather than left to be discovered by pressing them.
        let granted: Vec<String> = capability
            .permissions
            .iter()
            .map(|permission| permission.identifier().get().to_string())
            .collect();
        for needed in [
            // `apps/web/src/components/DesktopWindowControls.tsx`
            "core:window:allow-minimize",
            "core:window:allow-toggle-maximize",
            "core:window:allow-close",
            "core:window:allow-is-maximized",
            // Tauri's injected drag script, on `data-tauri-drag-region`
            "core:window:allow-start-dragging",
            "core:window:allow-internal-toggle-maximize",
        ] {
            assert!(
                granted.iter().any(|identifier| identifier == needed),
                "{needed} is not granted: the control that presses it does nothing"
            );
        }
    }

    /// The two halves, joined: the real bundle answered by the real policy.
    /// Everything else here is about the table; this is about the app opening.
    #[test]
    fn the_real_bundle_answers_the_window_through_the_servers_own_policy() {
        let ui = Assets::from_static(assets::FILES, assets::VERSION);

        let page = ui.resolve("/").expect("the window's first request");
        assert_eq!(page.path, "index.html");
        assert_eq!(page.content_type, "text/html; charset=utf-8");

        // The script the page names has to be there under its own name, or the
        // window opens on an empty document.
        let script = String::from_utf8_lossy(page.bytes);
        let source = script
            .split("src=\"")
            .nth(1)
            .and_then(|rest| rest.split('"').next())
            .expect("the entry point names a script");
        assert!(
            ui.resolve(source).is_some(),
            "the page asks for {source}, which is not in the bundle"
        );

        // And a route the client owns still lands on the page.
        assert_eq!(
            ui.resolve("/settings").expect("a client route").path,
            "index.html"
        );
    }
}
